---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Каждый язык должен содержать фотографию своей страны
  - Фильтр "Category" должен отсеивать лишние категории товаров
  - Выравнивание количества товаров в корзине должно быть единым
  - При возвращении из корзины на основную страницу должны сохраняться выбранные категории
  - Пользователь должен иметь право выбирать количество товара при добавлении его в корзину
  - Сайт должен содержать фильтрацию продуктов по возрастанию / по убыванию
  
